-- ============================================================================
-- Unified Chart of Accounts
--
-- Replaces the 3 separate tables (expense_categories, expense_subcategories,
-- coa_heads) with ONE flat table `coa_accounts` where every row is a
-- selectable leaf account:
--
--    code (auto-generated, immutable) │ subcategory │ category │ coa
--
-- The submitter picks a subcategory; the category + COA + code are all
-- derived by joining coa_accounts.id. That drops 2 dropdowns from the
-- request form and removes an entire class of "linked to a COA head"
-- master-data setup work.
--
-- code is auto-generated by a sequence, starts at max(existing) + 1 after
-- the initial import of Chart_of_Accounts.xlsx.
-- ============================================================================

-- 1. Build the new table.
create sequence if not exists coa_accounts_code_seq start with 1001;

create table if not exists coa_accounts (
  id uuid primary key default gen_random_uuid(),
  code integer not null unique default nextval('coa_accounts_code_seq'),
  subcategory text not null,
  category text not null,
  coa text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_coa_accounts_subcategory on coa_accounts(subcategory);
create index if not exists idx_coa_accounts_category on coa_accounts(category);
create index if not exists idx_coa_accounts_coa on coa_accounts(coa);

alter table coa_accounts enable row level security;

drop policy if exists "coa_accounts_read" on coa_accounts;
create policy "coa_accounts_read" on coa_accounts
  for select to authenticated using (true);

drop policy if exists "coa_accounts_admin_write" on coa_accounts;
create policy "coa_accounts_admin_write" on coa_accounts
  for insert to authenticated with check (has_role('admin'));

drop policy if exists "coa_accounts_admin_update" on coa_accounts;
create policy "coa_accounts_admin_update" on coa_accounts
  for update to authenticated
  using (has_role('admin')) with check (has_role('admin'));

drop policy if exists "coa_accounts_admin_delete" on coa_accounts;
create policy "coa_accounts_admin_delete" on coa_accounts
  for delete to authenticated using (has_role('admin'));

drop trigger if exists trg_coa_accounts_updated on coa_accounts;
create trigger trg_coa_accounts_updated
  before update on coa_accounts
  for each row execute function set_updated_at();

-- 2. Repoint payment_requests at the new table.
--    (We drop the old FKs and columns; there is no meaningful data on
--    Mumbai yet — this is a fresh project.)

alter table payment_requests drop constraint if exists payment_requests_category_id_fkey;
alter table payment_requests drop constraint if exists payment_requests_subcategory_id_fkey;
alter table payment_requests drop constraint if exists payment_requests_coa_head_id_fkey;
alter table payment_requests drop column if exists category_id;
alter table payment_requests drop column if exists subcategory_id;
alter table payment_requests drop column if exists coa_head_id;

alter table payment_requests
  add column if not exists coa_account_id uuid references coa_accounts(id) on delete restrict;

create index if not exists idx_requests_coa_account on payment_requests(coa_account_id);

-- 3. Rewrite coa_override_log to reference the new table.
alter table coa_override_log drop constraint if exists coa_override_log_old_coa_head_id_fkey;
alter table coa_override_log drop constraint if exists coa_override_log_new_coa_head_id_fkey;
alter table coa_override_log drop column if exists old_coa_head_id;
alter table coa_override_log drop column if exists new_coa_head_id;
alter table coa_override_log
  add column if not exists old_coa_account_id uuid references coa_accounts(id) on delete restrict,
  add column if not exists new_coa_account_id uuid references coa_accounts(id) on delete restrict;

-- 4. Drop the old tables.
drop table if exists expense_subcategories cascade;
drop table if exists expense_categories cascade;
drop table if exists coa_heads cascade;
