-- ============================================================================
-- Chart of Accounts sync from "CapEx COA Final App.xlsx" (141 source rows,
-- 14 COA heads, 48 categories).
--
-- The sheet is now the source of truth. Rows it doesn't list are DEACTIVATED
-- rather than deleted, so historical line items keep resolving.
--
-- A category whose sheet row has a blank Subcategory is chargeable at
-- category level; that is stored as a self-named anchor row
-- (subcategory = category), the same row a "whole category" charge resolves
-- to. Every category gets one so the optional third level always works.
-- ============================================================================

create temporary table desired_coa (coa text, category text, subcategory text) on commit drop;

insert into desired_coa (coa, category, subcategory) values
    ('Plant & Machinery', 'Food Processing Machinery', 'Industrial Mixer Grinder'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Single Stone Wet Grinder'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Tilting Wet Grinder'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Instant Rice Grinder'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Gravy Pulveriser'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Dough Kneader'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Vada Dropping Machine'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Vegetable Cutting Machine'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Potato Peeler Machine'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Peanut Peeling Machine'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Peanut Roaster'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Oil Dryer Machine'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Coldpress Juicer'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Centrifugal Juicer'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Chapathi Pressing Machine'),
    ('Plant & Machinery', 'Refrigeration & Cold Storage Equipment', 'Deep Freezer'),
    ('Plant & Machinery', 'Refrigeration & Cold Storage Equipment', 'Cold Room'),
    ('Plant & Machinery', 'Refrigeration & Cold Storage Equipment', 'Vertical Chiller'),
    ('Plant & Machinery', 'Refrigeration & Cold Storage Equipment', 'Undercounter Chiller'),
    ('Plant & Machinery', 'Refrigeration & Cold Storage Equipment', 'Visi Cooler'),
    ('Plant & Machinery', 'Washing, Cleaning & Safety Equipment', 'Dishwasher'),
    ('Plant & Machinery', 'Washing, Cleaning & Safety Equipment', 'Floor Scrubber'),
    ('Plant & Machinery', 'Washing, Cleaning & Safety Equipment', 'Vacuum Cleaner'),
    ('Plant & Machinery', 'Washing, Cleaning & Safety Equipment', 'Pressure & Spray Equipment'),
    ('Plant & Machinery', 'Washing, Cleaning & Safety Equipment', 'Fire Extinguisher'),
    ('Plant & Machinery', 'Water Purification & Supply Systems', 'RO Plant'),
    ('Plant & Machinery', 'Water Purification & Supply Systems', 'Water Pumpset'),
    ('Plant & Machinery', 'Water Purification & Supply Systems', 'Water Level Controller'),
    ('Plant & Machinery', 'Water Purification & Supply Systems', 'Geyser'),
    ('Plant & Machinery', 'Water Purification & Supply Systems', 'Water & Beverage Equipment'),
    ('Kitchen Equipment & Tools', 'Cooking Equipment & Exhaust Hoods', 'Cooking Range'),
    ('Kitchen Equipment & Tools', 'Cooking Equipment & Exhaust Hoods', 'Dosa Tawa'),
    ('Kitchen Equipment & Tools', 'Cooking Equipment & Exhaust Hoods', 'Roti Tawa'),
    ('Kitchen Equipment & Tools', 'Cooking Equipment & Exhaust Hoods', 'Idli Steamer'),
    ('Kitchen Equipment & Tools', 'Cooking Equipment & Exhaust Hoods', 'Induction Stove & Microwave Oven'),
    ('Kitchen Equipment & Tools', 'Cooking Equipment & Exhaust Hoods', 'Gas Boiler'),
    ('Kitchen Equipment & Tools', 'Cooking Equipment & Exhaust Hoods', 'Coffee Machine'),
    ('Kitchen Equipment & Tools', 'Kitchen Workstations, Sinks & Material Handling Equipment', 'SS Work Table'),
    ('Kitchen Equipment & Tools', 'Kitchen Workstations, Sinks & Material Handling Equipment', 'Batter Table'),
    ('Kitchen Equipment & Tools', 'Kitchen Workstations, Sinks & Material Handling Equipment', 'Dish Wash Entry & Exit Table'),
    ('Kitchen Equipment & Tools', 'Kitchen Workstations, Sinks & Material Handling Equipment', 'Kitchen & Material Handling Trolley'),
    ('Kitchen Equipment & Tools', 'Kitchen Workstations, Sinks & Material Handling Equipment', 'SS Pallet'),
    ('Kitchen Equipment & Tools', 'Kitchen Workstations, Sinks & Material Handling Equipment', 'Kitchen Sinks & Drain Fittings'),
    ('Kitchen Equipment & Tools', 'Kitchen Workstations, Sinks & Material Handling Equipment', 'Crates & Shipper Boxes'),
    ('Kitchen Equipment & Tools', 'Storage Racks & Shelving', 'SS Storage Rack'),
    ('Kitchen Equipment & Tools', 'Storage Racks & Shelving', 'MS Storage Rack'),
    ('Kitchen Equipment & Tools', 'Storage Racks & Shelving', 'Cold Room Rack'),
    ('Kitchen Equipment & Tools', 'Storage Racks & Shelving', 'Pot Rack'),
    ('Kitchen Equipment & Tools', 'Storage Racks & Shelving', 'Overhead & Wall Mounted Shelf'),
    ('Kitchen Equipment & Tools', 'Service Counters, Display & Food Holding Units', 'Service & Display Counter'),
    ('Kitchen Equipment & Tools', 'Service Counters, Display & Food Holding Units', 'Bain Marie & Food Holding Equipment'),
    ('Kitchen Equipment & Tools', 'Gas Supply Infrastructure', 'Gas Pipeline'),
    ('Kitchen Equipment & Tools', 'Gas Supply Infrastructure', 'LOT Gas System'),
    ('Kitchen Equipment & Tools', 'Kitchen Utensils, Tools & Serviceware', 'Aluminium Cooking Vessels'),
    ('Kitchen Equipment & Tools', 'Kitchen Utensils, Tools & Serviceware', 'SS Cooking Vessels'),
    ('Kitchen Equipment & Tools', 'Kitchen Utensils, Tools & Serviceware', 'GN Pans'),
    ('Kitchen Equipment & Tools', 'Kitchen Utensils, Tools & Serviceware', 'Serving Ware & Crockery'),
    ('Kitchen Equipment & Tools', 'Kitchen Utensils, Tools & Serviceware', 'Sealing & Packaging Tools'),
    ('Kitchen Equipment & Tools', 'Kitchen Utensils, Tools & Serviceware', 'Weighing Scale'),
    ('Kitchen Equipment & Tools', 'Kitchen Utensils, Tools & Serviceware', 'Miscellaneous Kitchen Equipment'),
    ('Furniture & Fixtures', 'Dining Furniture', 'Dining Table'),
    ('Furniture & Fixtures', 'Dining Furniture', 'Dining Chair'),
    ('Furniture & Fixtures', 'Dining Furniture', 'Queue Manager'),
    ('Furniture & Fixtures', 'Office Furniture', 'Office Table'),
    ('Furniture & Fixtures', 'Office Furniture', 'Office Chair'),
    ('Furniture & Fixtures', 'Office Furniture', 'Storage Furniture'),
    ('Furniture & Fixtures', 'Other Furniture & Fixtures', 'Other Furniture & Fixtures'),
    ('Computers & IT Equipment', 'Computers & Peripherals', 'Desktop Computer'),
    ('Computers & IT Equipment', 'Computers & Peripherals', 'Laptop Computer'),
    ('Computers & IT Equipment', 'Computers & Peripherals', 'CPU & Monitor'),
    ('Computers & IT Equipment', 'Computers & Peripherals', 'Office Printer'),
    ('Computers & IT Equipment', 'POS & Outlet Technology Hardware', 'POS Machine'),
    ('Computers & IT Equipment', 'POS & Outlet Technology Hardware', 'Cash Drawer'),
    ('Computers & IT Equipment', 'POS & Outlet Technology Hardware', 'KDS Display'),
    ('Computers & IT Equipment', 'POS & Outlet Technology Hardware', 'Kiosk Machine'),
    ('Computers & IT Equipment', 'POS & Outlet Technology Hardware', 'KOT Printer'),
    ('Computers & IT Equipment', 'Networking, Security & Communication Systems', 'CCTV Setup'),
    ('Computers & IT Equipment', 'Networking, Security & Communication Systems', 'Biometric Attendance System'),
    ('Computers & IT Equipment', 'Networking, Security & Communication Systems', 'Intercom & Telephone System'),
    ('Computers & IT Equipment', 'Networking, Security & Communication Systems', 'Walkie Talkie & Communication System'),
    ('Computers & IT Equipment', 'Networking, Security & Communication Systems', 'Digital Locker'),
    ('Computers & IT Equipment', 'Networking, Security & Communication Systems', 'Mobile Phone & Tablet'),
    ('Computers & IT Equipment', 'Audio Visual & Display Systems', 'Television'),
    ('Computers & IT Equipment', 'Audio Visual & Display Systems', 'Commercial Display Unit'),
    ('Computers & IT Equipment', 'Audio Visual & Display Systems', 'Android Box'),
    ('Computers & IT Equipment', 'Audio Visual & Display Systems', 'Projector'),
    ('Computers & IT Equipment', 'Audio Visual & Display Systems', 'Amplifier & Speaker System'),
    ('Electrical & HVAC Installations', 'Power Distribution, Control & Backup Systems', 'Electrical Distribution Board'),
    ('Electrical & HVAC Installations', 'Power Distribution, Control & Backup Systems', 'Cold Storage Temperature Monitoring System'),
    ('Electrical & HVAC Installations', 'Power Distribution, Control & Backup Systems', 'Servo Stabilizer'),
    ('Electrical & HVAC Installations', 'Power Distribution, Control & Backup Systems', 'Transformer Yard Setup'),
    ('Electrical & HVAC Installations', 'Power Distribution, Control & Backup Systems', 'UPS & Battery Bank'),
    ('Electrical & HVAC Installations', 'Air Conditioning, Ventilation & Cooling Systems', 'Customer Area AC & HVAC System'),
    ('Electrical & HVAC Installations', 'Air Conditioning, Ventilation & Cooling Systems', 'Kitchen Ventilation & Exhaust System'),
    ('Electrical & HVAC Installations', 'Air Conditioning, Ventilation & Cooling Systems', 'Exhaust Hood'),
    ('Electrical & HVAC Installations', 'Air Conditioning, Ventilation & Cooling Systems', 'Fans & Air Coolers'),
    ('Motor Vehicles', 'Electric Vehicles', 'Three Wheeler EV'),
    ('Motor Vehicles', 'ICE Vehicles', 'ICE Vehicles'),
    ('Building & Civil Structure', 'Structural & Civil Works - Materials', 'Structural & Civil Works - Materials'),
    ('Building & Civil Structure', 'Structural & Civil Works - Labor', 'Structural & Civil Works - Labor'),
    ('Building & Civil Structure', 'Structural & Civil Works - Contractor Fees', 'Structural & Civil Works - Contractor Fees'),
    ('Interior Fit-out & Branding', 'Interior & Branding Works - Materials', 'Interior & Branding Works - Materials'),
    ('Interior Fit-out & Branding', 'Interior & Branding Works - Labor', 'Interior & Branding Works - Labor'),
    ('Interior Fit-out & Branding', 'Interior & Branding Works - Contractor Fees', 'Interior & Branding Works - Contractor Fees'),
    ('Plumbing & Sanitary Infrastructure', 'Plumbing & Sanitary Works - Materials', 'Plumbing & Sanitary Works - Materials'),
    ('Plumbing & Sanitary Infrastructure', 'Plumbing & Sanitary Works - Labor', 'Plumbing & Sanitary Works - Labor'),
    ('Plumbing & Sanitary Infrastructure', 'Plumbing & Sanitary Works - Contractor Fees', 'Plumbing & Sanitary Works - Contractor Fees'),
    ('Electrical Wiring & Lighting', 'Electrical Wiring & Lighting - Materials', 'Electrical Wiring & Lighting - Materials'),
    ('Electrical Wiring & Lighting', 'Electrical Wiring & Lighting - Labor', 'Electrical Wiring & Lighting - Labor'),
    ('Electrical Wiring & Lighting', 'Electrical Wiring & Lighting - Contractor Fees', 'Electrical Wiring & Lighting - Contractor Fees'),
    ('Building Services & Utilities', 'Building Services & Utilities - Materials', 'Building Services & Utilities - Materials'),
    ('Building Services & Utilities', 'Building Services & Utilities - Labor', 'Building Services & Utilities - Labor'),
    ('Building Services & Utilities', 'Building Services & Utilities - Contractor Fees', 'Building Services & Utilities - Contractor Fees'),
    ('Travel, Supervision & Site Costs - WIP', 'Travel & Conveyance', 'Travel & Conveyance'),
    ('Travel, Supervision & Site Costs - WIP', 'Site Supervision Costs', 'Site Supervision Costs'),
    ('Travel, Supervision & Site Costs - WIP', 'Daily Allowances & Food', 'Daily Allowances & Food'),
    ('Building & Civil Structure', 'Professional Fees & Approvals', 'Architectural & Design Fees'),
    ('Building & Civil Structure', 'Professional Fees & Approvals', 'Engineering & Consulting Fees'),
    ('Building & Civil Structure', 'Professional Fees & Approvals', 'Government Approvals & Permits'),
    ('Building & Civil Structure', 'Professional Fees & Approvals', 'Property Acquisition Costs'),
    ('Security Deposits', 'Building & Premises Deposits', 'Outlet Premises Deposit'),
    ('Security Deposits', 'Building & Premises Deposits', 'Parking Space Deposit'),
    ('Security Deposits', 'Building & Premises Deposits', 'Staff Room Deposit'),
    ('Security Deposits', 'Utility Connection Deposits', 'Electricity Connection Deposit (BESCOM)'),
    ('Security Deposits', 'Utility Connection Deposits', 'Gas Connection Deposit (GAIL)'),
    ('Security Deposits', 'Utility Connection Deposits', 'Water & Sewage Connection Deposit (BWSSB)'),
    ('Security Deposits', 'Equipment Rental Deposits', 'Equipment Rental Deposits'),
    ('Pre-Operative Expenses', 'Pre-Opening Staff Costs', 'Pre-Opening Salaries & Wages'),
    ('Pre-Operative Expenses', 'Pre-Opening Staff Costs', 'Pre-Opening Training Costs'),
    ('Pre-Operative Expenses', 'Pre-Opening Staff Costs', 'Pre-Opening Recruitment Costs'),
    ('Pre-Operative Expenses', 'Pre-Opening Staff Costs', 'Pre-Opening Security Staff Costs'),
    ('Pre-Operative Expenses', 'Pre-Opening Rentals & Facility Costs', 'Pre-Opening Building Rent'),
    ('Pre-Operative Expenses', 'Pre-Opening Rentals & Facility Costs', 'Pre-Opening Equipment Rental'),
    ('Pre-Operative Expenses', 'Pre-Opening Rentals & Facility Costs', 'Pre-Opening Utility Costs'),
    ('Pre-Operative Expenses', 'Pre-Opening Materials & Consumption', 'Pre-Opening Raw Materials Consumption'),
    ('Pre-Operative Expenses', 'Pre-Opening Materials & Consumption', 'Pre-Opening Packaging Materials Consumption'),
    ('Pre-Operative Expenses', 'Pre-Opening Materials & Consumption', 'Pre-Opening Housekeeping Materials Consumption'),
    ('Pre-Operative Expenses', 'Pre-Opening Marketing & Launch', 'Pre-Opening Launch Event Expenses'),
    ('Pre-Operative Expenses', 'Pre-Opening Marketing & Launch', 'Pre-Opening Marketing & Advertising'),
    ('Pre-Operative Expenses', 'Pre-Opening Marketing & Launch', 'Pre-Opening Promotional Food Sampling'),
    ('Pre-Operative Expenses', 'Pre-Opening Miscellaneous', 'Pre-Opening Miscellaneous'),
    ('Plant & Machinery', 'Food Processing Machinery', 'Food Processing Machinery'),
    ('Plant & Machinery', 'Refrigeration & Cold Storage Equipment', 'Refrigeration & Cold Storage Equipment'),
    ('Plant & Machinery', 'Washing, Cleaning & Safety Equipment', 'Washing, Cleaning & Safety Equipment'),
    ('Plant & Machinery', 'Water Purification & Supply Systems', 'Water Purification & Supply Systems'),
    ('Kitchen Equipment & Tools', 'Cooking Equipment & Exhaust Hoods', 'Cooking Equipment & Exhaust Hoods'),
    ('Kitchen Equipment & Tools', 'Kitchen Workstations, Sinks & Material Handling Equipment', 'Kitchen Workstations, Sinks & Material Handling Equipment'),
    ('Kitchen Equipment & Tools', 'Storage Racks & Shelving', 'Storage Racks & Shelving'),
    ('Kitchen Equipment & Tools', 'Service Counters, Display & Food Holding Units', 'Service Counters, Display & Food Holding Units'),
    ('Kitchen Equipment & Tools', 'Gas Supply Infrastructure', 'Gas Supply Infrastructure'),
    ('Kitchen Equipment & Tools', 'Kitchen Utensils, Tools & Serviceware', 'Kitchen Utensils, Tools & Serviceware'),
    ('Furniture & Fixtures', 'Dining Furniture', 'Dining Furniture'),
    ('Furniture & Fixtures', 'Office Furniture', 'Office Furniture'),
    ('Computers & IT Equipment', 'Computers & Peripherals', 'Computers & Peripherals'),
    ('Computers & IT Equipment', 'POS & Outlet Technology Hardware', 'POS & Outlet Technology Hardware'),
    ('Computers & IT Equipment', 'Networking, Security & Communication Systems', 'Networking, Security & Communication Systems'),
    ('Computers & IT Equipment', 'Audio Visual & Display Systems', 'Audio Visual & Display Systems'),
    ('Electrical & HVAC Installations', 'Power Distribution, Control & Backup Systems', 'Power Distribution, Control & Backup Systems'),
    ('Electrical & HVAC Installations', 'Air Conditioning, Ventilation & Cooling Systems', 'Air Conditioning, Ventilation & Cooling Systems'),
    ('Motor Vehicles', 'Electric Vehicles', 'Electric Vehicles'),
    ('Building & Civil Structure', 'Professional Fees & Approvals', 'Professional Fees & Approvals'),
    ('Security Deposits', 'Building & Premises Deposits', 'Building & Premises Deposits'),
    ('Security Deposits', 'Utility Connection Deposits', 'Utility Connection Deposits'),
    ('Pre-Operative Expenses', 'Pre-Opening Staff Costs', 'Pre-Opening Staff Costs'),
    ('Pre-Operative Expenses', 'Pre-Opening Rentals & Facility Costs', 'Pre-Opening Rentals & Facility Costs'),
    ('Pre-Operative Expenses', 'Pre-Opening Materials & Consumption', 'Pre-Opening Materials & Consumption'),
    ('Pre-Operative Expenses', 'Pre-Opening Marketing & Launch', 'Pre-Opening Marketing & Launch');

-- 1. Add anything new.
insert into coa_accounts (coa, category, subcategory)
select d.coa, d.category, d.subcategory
from desired_coa d
where not exists (
  select 1 from coa_accounts a
  where a.coa = d.coa and a.category = d.category and a.subcategory = d.subcategory
);

-- 2. Reactivate anything previously retired that is back in the sheet.
update coa_accounts a set is_active = true
from desired_coa d
where a.coa = d.coa and a.category = d.category and a.subcategory = d.subcategory
  and a.is_active = false;

-- 3. Retire whatever the sheet no longer lists (kept for referential history).
update coa_accounts a set is_active = false
where a.is_active = true
  and not exists (
    select 1 from desired_coa d
    where d.coa = a.coa and d.category = a.category and d.subcategory = a.subcategory
  );
